# Generated by Django 5.1.2 on 2024-10-25 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EVType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("battery_capacity_kwh", models.FloatField()),
                ("efficiency_kwh_per_km", models.FloatField()),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("distance_km", models.FloatField()),
                ("estimated_charge_used_kwh", models.FloatField()),
                (
                    "ev_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charge_estimation.evtype",
                    ),
                ),
            ],
        ),
    ]
