# Generated by Django 5.1.2 on 2024-10-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charge_estimation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journey",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="journey",
            name="ev_type",
        ),
        migrations.RemoveField(
            model_name="journey",
            name="origin",
        ),
        migrations.AddField(
            model_name="journey",
            name="destination_latitude",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="journey",
            name="destination_longitude",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="journey",
            name="origin_latitude",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="journey",
            name="origin_longitude",
            field=models.FloatField(default=0),
        ),
    ]
