# Generated by Django 5.1.2 on 2024-10-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "charge_estimation",
            "0004_rename_estimated_charge_used_kwh_journey_charge_used_kwh",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="percentage_charge_used",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="journey",
            name="round_trip_charge_used_kwh",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="journey",
            name="round_trip_percentage_used",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="journey",
            name="charge_used_kwh",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="journey",
            name="distance_km",
            field=models.FloatField(default=0),
        ),
    ]
