# Generated by Django 5.1.2 on 2024-10-29 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charge_estimation", "0006_journey_driving_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="destination",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="origin",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="charge_used_kwh",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="destination_latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="destination_longitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="distance_km",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="ev_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="charge_estimation.evtype",
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="origin_latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="origin_longitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="percentage_charge_used",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="round_trip_charge_used_kwh",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="round_trip_percentage_used",
            field=models.FloatField(null=True),
        ),
    ]
