# Generated by Django 5.1.2 on 2024-10-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charge_estimation", "0007_journey_destination_journey_origin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="driving_style",
            field=models.CharField(
                choices=[
                    ("VERY_EFFICIENT", 0.75),
                    ("EFFICIENT", 1.0),
                    ("REGULAR", 1.25),
                    ("AGGRESSIVE", 1.5),
                    ("VERY_AGGRESSIVE", 1.75),
                ],
                default="REGULAR",
                max_length=20,
            ),
        ),
    ]
